# Generated by Django 3.1.7 on 2021-02-23 18:58

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_contact', models.CharField(max_length=32)),
                ('reserved', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('cancelled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ReservationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_type', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('seats_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screening_start', models.DateTimeField(default=datetime.datetime(2021, 2, 23, 18, 58, 24, 495916, tzinfo=utc))),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.room')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('number', models.IntegerField()),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.room')),
            ],
        ),
        migrations.CreateModel(
            name='SeatReserved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.reservation')),
                ('screening_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.screening')),
                ('seat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.seat')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.reservationtype'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='screening_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.screening'),
        ),
    ]
