# Generated by Django 3.1.7 on 2021-03-05 12:02

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('director', models.CharField(max_length=256)),
                ('cast_members', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('movie_duration', models.IntegerField()),
                ('tickets_sold', models.IntegerField(default=0)),
                ('certificate', models.CharField(default='U', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_type', models.CharField(choices=[('ADULT', 'Adult'), ('CHILD', 'Child'), ('SENIOR', 'Senior'), ('STUDENT', 'Student')], default='ADULT', max_length=32)),
                ('reservation_contact', models.CharField(max_length=32)),
                ('reserved', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('cancelled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField()),
                ('seats_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screening_start', models.DateTimeField(default=datetime.datetime(2021, 3, 5, 12, 2, 52, 11123, tzinfo=utc))),
                ('movie_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.movie')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.room')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('number', models.IntegerField()),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.room')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32, null=True)),
                ('last_name', models.CharField(max_length=32, null=True)),
                ('user_name', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=32)),
                ('password', models.CharField(max_length=32, validators=[django.core.validators.MinLengthValidator(8)])),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('CARD', 'Card Payment'), ('CASH', 'Cash Payment')], default='CARD', max_length=32)),
                ('date_time', models.DateTimeField(default=datetime.datetime(2021, 3, 5, 12, 2, 51, 974286, tzinfo=utc))),
                ('amount', models.FloatField()),
                ('successful', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.user')),
            ],
        ),
        migrations.CreateModel(
            name='SeatReserved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.reservation')),
                ('screening_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.screening')),
                ('seat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.seat')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='screening_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.screening'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.user'),
        ),
    ]
