# Generated by Django 3.1.7 on 2021-03-05 18:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20210305_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='static/customer/img/qr_codes'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='screening_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 5, 18, 53, 23, 501345, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 5, 18, 53, 23, 455035, tzinfo=utc)),
        ),
    ]
