# Generated by Django 3.1.7 on 2021-02-24 16:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20210224_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screening',
            name='screening_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 24, 16, 59, 14, 103826, tzinfo=utc)),
        ),
    ]
