# Generated by Django 3.1.7 on 2021-02-26 15:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_auto_20210224_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screening',
            name='screening_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 26, 15, 10, 23, 470256, tzinfo=utc)),
        ),
    ]
