# Generated by Django 3.1.7 on 2021-02-26 22:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_auto_20210226_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('director', models.CharField(max_length=256)),
                ('cast_members', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('movie_duration', models.IntegerField(default=1)),
                ('tickets_sold', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='screening',
            name='screening_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 26, 22, 34, 15, 368574, tzinfo=utc)),
        ),
    ]
