# Generated by Django 3.1.7 on 2021-02-26 22:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_auto_20210226_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screening',
            name='screening_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 26, 22, 36, 26, 931515, tzinfo=utc)),
        ),
    ]
