# Generated by Django 3.1.7 on 2021-03-04 09:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0012_auto_20210303_1856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='used_id',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='screening',
            name='screening_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 4, 9, 33, 43, 972108, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 4, 9, 33, 43, 926746, tzinfo=utc)),
        ),
    ]
