# Generated by Django 3.1.7 on 2021-03-04 22:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0014_auto_20210304_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='certificate',
            field=models.CharField(default='U', max_length=2),
        ),
        migrations.AlterField(
            model_name='screening',
            name='screening_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 4, 22, 49, 40, 311463, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 4, 22, 49, 40, 140979, tzinfo=utc)),
        ),
    ]
