# Generated by Django 3.1.7 on 2021-03-05 09:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0016_auto_20210304_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='screening',
            name='screening_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 5, 9, 33, 40, 925101, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 5, 9, 33, 40, 894104, tzinfo=utc)),
        ),
    ]
