# Generated by Django 3.1.7 on 2021-03-05 01:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0016_auto_20210304_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='screening_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 5, 1, 54, 46, 314178, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 5, 1, 54, 46, 62440, tzinfo=utc)),
        ),
    ]
