# Generated by Django 3.1.7 on 2021-03-09 00:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0016_auto_20210304_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='static/customer/img/qr_codes'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='screening',
            name='screening_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 9, 0, 30, 31, 389540, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 9, 0, 30, 31, 342350, tzinfo=utc)),
        ),
    ]
