# Generated by Django 3.1.7 on 2021-03-09 00:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0017_auto_20210309_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster_img',
            field=models.ImageField(default='static/customer/img/default_movie.jpg', upload_to='static/customer/img/'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='screening_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 9, 0, 55, 40, 302877, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 9, 0, 55, 40, 255110, tzinfo=utc)),
        ),
    ]
