# Generated by Django 3.1.7 on 2021-03-05 03:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0018_auto_20210305_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster_img',
            field=models.ImageField(default='static/customer/img/default_movie.jpg', upload_to='static/customer/img/'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='screening_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 5, 3, 17, 36, 868125, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 5, 3, 17, 36, 728127, tzinfo=utc)),
        ),
    ]
