# Generated by Django 3.1.7 on 2021-03-12 20:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0019_auto_20210312_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='screening',
            name='screening_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 12, 20, 25, 25, 609486, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 12, 20, 25, 25, 571260, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
