# Generated by Django 3.1.7 on 2021-03-16 14:44

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0025_auto_20210315_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reserved_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 16, 14, 44, 27, 375974, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='reservation',
            name='transaction_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.transaction'),
        ),
    ]
