# Generated by Django 3.1.7 on 2021-03-16 14:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0026_auto_20210316_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reserved_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
