# Generated by Django 3.1.7 on 2021-03-16 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0027_auto_20210316_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='reservation_contact',
        ),
    ]
