# Generated by Django 3.1.7 on 2021-03-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0028_remove_reservation_reservation_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
