# Generated by Django 3.1.7 on 2021-03-16 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0030_reservation_lead_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.reservation'),
        ),
    ]
