# Generated by Django 3.1.7 on 2021-03-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0034_auto_20210321_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='total_income',
            field=models.IntegerField(default=0),
        ),
    ]
