# Generated by Django 3.1.7 on 2021-03-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0034_auto_20210321_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
