# Generated by Django 3.1.7 on 2021-03-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0035_auto_20210328_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='total_income',
            field=models.IntegerField(default=0),
        ),
    ]
