# Generated by Django 3.1.7 on 2021-03-29 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0036_movie_total_income'),
        ('API', '0035_movie_total_income'),
    ]

    operations = [
    ]
