# Generated by Django 3.1.7 on 2021-02-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('director', models.CharField(max_length=256)),
                ('cast_members', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('movie_poster', models.ImageField(blank=True, upload_to='Movie_images')),
                ('movie_duration', models.IntegerField(default=1)),
                ('tickets_sold', models.IntegerField(default=0)),
            ],
        ),
    ]
