# Generated by Django 3.1.7 on 2021-02-24 17:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('API_reservations', '0004_auto_20210224_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screening',
            name='screening_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 24, 17, 36, 52, 259912, tzinfo=utc)),
        ),
    ]
